// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcB0-ayrnEtRKl3rzK0nI_MqGSOK0fXWg',
    appId: '1:726383292908:web:bae6ecfe24e6814b5b50c9',
    messagingSenderId: '726383292908',
    projectId: 'assisthub-59ed4',
    authDomain: 'assisthub-59ed4.firebaseapp.com',
    storageBucket: 'assisthub-59ed4.firebasestorage.app',
    measurementId: 'G-TYHZFHFL47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGIiT3SNOGa321Hrv2mwfEY_ByEkAjVc',
    appId: '1:726383292908:android:80014014458a3d1e5b50c9',
    messagingSenderId: '726383292908',
    projectId: 'assisthub-59ed4',
    storageBucket: 'assisthub-59ed4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcB0-ayrnEtRKl3rzK0nI_MqGSOK0fXWg',
    appId: '1:726383292908:web:6620f5e4a5a2b62a5b50c9',
    messagingSenderId: '726383292908',
    projectId: 'assisthub-59ed4',
    authDomain: 'assisthub-59ed4.firebaseapp.com',
    storageBucket: 'assisthub-59ed4.firebasestorage.app',
    measurementId: 'G-0EG9624G2P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlTXD3d888pO_ydSLg-3A-I2S5fbJYgiM',
    appId: '1:726383292908:ios:51efee1cfbb74e3f5b50c9',
    messagingSenderId: '726383292908',
    projectId: 'assisthub-59ed4',
    storageBucket: 'assisthub-59ed4.firebasestorage.app',
    androidClientId: '726383292908-huuetnku6auct304e4gc4kssrot4himh.apps.googleusercontent.com',
    iosClientId: '726383292908-q2ec45m5571363u2tjuga99jcmjiugtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.assisthub',
  );

}